name: "CI"
on: [push, pull_request]

permissions:
  contents: read
jobs:
  textlint:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [ 18 ]

    name: Textlint(Node ${{ matrix.node }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - name: Install
        run: npm ci
      - name: Textlint
        run: |
          npm run textlint